sonar.projectKey=psw-pipeline-base
sonar.projectName=PSW Pipeline Base
sonar.projectVersion=0.0.1
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
